[AppKey]
id = "ID_GOES_HERE"                 # ID for B2
key = "KEY_GOES_HERE"               # API key for B2

[bucket]
name = "bot"                        # B2 Bucket Name
backup_folder_name = "backups"      # Name of folder for backups to be stored in
