# This file is for enabling/disabling bot extensions
#   See config.toml for controlling music

# Background : Functions that run in background
background = [
    "quotes"
]
# Bot : Related to bot management and development.
bot = [
    "bot_cmds"
]

# Economy [Backburner] : Economy related commands
#economy = [
#    "economy", # This is required for all others in this cog and must be first in the list.
#    "gamble"
#]

# Fun : Entertainment and enjoyment commands.
fun = [ 
    "battleroyale",
    "fun",
    "hangman",
    "numberguess", 
    "nsfw",
    "pressbutton", 
    "rroulette", 
    "speedtype", 
    "sudoku", 
    "trivia", 
    "userguess", 
    "wouldyourather", 
    "xkcd"
]

# Images: Image Generation and Modification
images = [ 
    "memes"
]

# Info: Information Commands
info = [ 
    "celebbday",
    "corona", 
    "curseforge",
    "dictionary", 
    "info", 
    "stock",
    "trackergg",
    "urbandict", 
    "wikipedia"
]

# Owner: Bot Owner-only commands
owner = [
    "modules",
    "owner"
]

# Preferences: Preference Management
preferences = [ 
    "userprefs"
]

# ServMng: Server Management commands
servmng = [
    "defrole",
    "reactionroles", 
    "rules", 
    "rum", 
    "servmng", 
    "temprole"
]

# Utility: Utility-based commands
utility = [ 
    "announce",
    "cmdsearch",
    "colorgen",
    "customcommand",
    "lyrics", 
    "memesearch",
    "palette",
    "poll", 
    "progress", 
    "random",
    "stega", 
    "tags",
    "threads",
#    "twitter",
    "utility"
]

# None: Misc commands not found in a module/cog.
none = [ 
    "errors",
    "support"
]
