extensions = [
    "background.command_logger",
    "bot.bot_cmds",
    "errors",
    "fun.fun",
    "fun.minesweeper",
    "fun.numberguess",
    "fun.pressbutton",
    "fun.rroulette",
    "fun.speedtype",
    "fun.sudoku",
    "fun.trivia",
    "fun.userguess",
    "fun.wouldyourather",
    "fun.xkcd",
    "images.memes",
    "info.corona",
    "info.dictionary",
    "info.info",
    "info.stock",
    "info.urbandict",
    "info.wikipedia",
    "owner",
    "preferences.userprefs",
    "servmng.reactionroles",
    "servmng.rules",
    "servmng.rum",
    "servmng.servmng",
    "servmng.temprole",
    "utility.announce",
    "utility.autourlshort",
    "utility.colorgen",
    "utility.lyrics",
    "utility.memesearch",
    "utility.poll",
    "utility.progress",
    "utility.random",
    "utility.reddit",
    "utility.stega",
    "utility.tags",
    "utility.utility"
]


def get_extensions():
    return extensions
