extensions = [
    "background.command_logger",
    "bot.bot_cmds",
    "errors",
    "fun.fun",
    "fun.minesweeper",
    "fun.numberguess",
    "fun.pressbutton",
    "fun.rroulette",
    "fun.speedtype",
    "fun.sudoku",
    "fun.trivia",
    "fun.userguess",
    "fun.wouldyourather",
    "fun.xkcd",
    "images.fakeping",
    "images.manip",
    "images.memelicense",
    "images.memes",
    "info",
    "owner",
    "preferences.userprefs",
    "servmng.reactionroles",
    "servmng.rules",
    "servmng.rum",
    "servmng.servmng",
    "utility.announce",
    "utility.colorgen",
    "utility.corona",
    "utility.dictionary",
    "utility.lyrics",
    "utility.memesearch",
    "utility.poll",
    "utility.progress",
    "utility.random",
    "utility.reddit",
    "utility.tags",
    "utility.urbandict",
    "utility.utility",
    "utility.wikipedia"
]


def get_extensions():
    return extensions

