# Bot : Related to bot management and development.
bot = [
    "bot_cmds"
]

# Fun : Entertainment and enjoyment commands.
fun = [ 
    "battleroyale", 
    "blackjack", 
    "fun",
    "hangman",
    "minesweeper", 
    "numberguess", 
    "pressbutton", 
    "rroulette", 
    "speedtype", 
    "sudoku", 
    "trivia", 
    "userguess", 
    "wouldyourather", 
    "xkcd"
]

# Images: Image Generation and Modification
images = [ 
    "memes"
]

# Info: Information Commands
info = [ 
    "corona", 
    "curseforge",
    "dictionary", 
    "info", 
    "stock", 
    "urbandict", 
    "wikipedia"
]

# Preferences: Preference Management
preferences = [ 
    "userprefs"
]

# ServMng: Server Management commands
servmng = [ 
    "reactionroles", 
    "rules", 
    "rum", 
    "servmng", 
    "temprole"
]

# Utility: Utility-based commands
utility = [ 
    "announce", 
    "autourlshort", 
    "colorgen", 
    "lyrics", 
    "memesearch", 
    "poll", 
    "progress", 
    "random", 
    "reddit", 
    "stega", 
    "tags", 
    "utility"
]

# None: Misc commands not found in a module/cog.
none = [ 
    "errors", 
    "owner"
]
